# Generated by Django 5.2.17 on 2026-08-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('published', 'Published'), ('hidden', 'Hidden')], db_index=True, default='submitted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'slug'], name='nuances_nua_kind_fb7935_idx')],
            },
        ),
    ]
