# Generated by Django 5.2.17 on 2026-08-20 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('workspace_name', models.CharField(max_length=255)),
                ('workspace_slug', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('us', 'US'), ('eu', 'EU')], default='us', max_length=8)),
                ('encrypted_token', models.BinaryField()),
                ('token_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['workspace_id', '-last_seen_at'], name='auth_worksp_workspa_1284b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'token_fingerprint'), name='uniq_workspace_token')],
            },
        ),
        migrations.CreateModel(
            name='WriteKeyRevealAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('source_id', models.CharField(max_length=255)),
                ('revealed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'indexes': [models.Index(fields=['workspace_id', '-revealed_at'], name='auth_worksp_workspa_24abeb_idx')],
            },
        ),
    ]
