# Generated by Django 5.2.17 on 2026-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesession',
            name='encrypted_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacesession',
            name='token_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
