# Generated by Django 5.2.17 on 2026-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_workspace', '0002_alter_workspacesession_encrypted_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesession',
            name='credential_kind',
            field=models.CharField(blank=True, choices=[('public_api', 'Public API token'), ('graphql', 'App session (auth_token)')], default='public_api', max_length=16),
        ),
    ]
