# Generated by Django 5.2.17 on 2026-09-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth_workspace', '0003_workspacesession_credential_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspacesession',
            name='uniq_workspace_token',
        ),
        migrations.AddField(
            model_name='workspacesession',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='workspacesession',
            name='anon_scope',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='workspacesession',
            name='workspace_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='workspacesession',
            index=models.Index(fields=['account', '-last_seen_at'], name='auth_worksp_account_474a2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacesession',
            constraint=models.UniqueConstraint(condition=models.Q(('encrypted_token__isnull', False)), fields=('workspace_id', 'token_fingerprint'), name='uniq_workspace_token'),
        ),
    ]
