# Generated by Django 5.2.17 on 2026-09-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth_workspace', '0005_split_anon_scope_from_workspace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorWorkspaceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('workspace_id', models.CharField(max_length=64)),
                ('workspace_name', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_workspace_bookmarks', to='accounts.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'slug'), name='uniq_account_bookmark_slug')],
            },
        ),
    ]
