# Generated by Django 5.2.17 on 2026-09-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='anon_scope',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='diagram',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='shared_with_workspace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='workspace_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='diagram',
            index=models.Index(fields=['owner', '-updated_at'], name='diagrams_di_owner_i_213c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='diagram',
            index=models.Index(fields=['anon_scope', '-updated_at'], name='diagrams_di_anon_sc_7f6ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='diagram',
            index=models.Index(fields=['workspace_id', 'shared_with_workspace'], name='diagrams_di_workspa_72e032_idx'),
        ),
    ]
