# Generated by Django 5.2.17 on 2026-08-20 05:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('source', 'Source'), ('destination', 'Destination'), ('warehouse', 'Warehouse')], db_index=True, max_length=16)),
                ('metadata_id', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('logo_url', models.URLField(blank=True, max_length=1024)),
                ('docs_url', models.URLField(blank=True, max_length=1024)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'slug'], name='catalog_cat_kind_c42ca3_idx'), models.Index(fields=['kind', 'name'], name='catalog_cat_kind_14b660_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'metadata_id'), name='uniq_catalog_component')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceResourceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('resource_type', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'resource_type'), name='uniq_ws_resource')],
            },
        ),
    ]
